#!/bin/bash
# Update dotfiles within your home folder


if [ $1 = "dot.emacs" ]; then
    cat $HOME/.emacs | tee $HOME/.emacs.dotbak &> /dev/null 
    cat ./dot.emacs | tee $HOME/.emacs &> /dev/null
else
    echo "wrong parameter passed!"
fi
